# deploy.yml
---
- name: Deploy Flask App with Nginx and Gunicorn
  hosts: webservers
  become: yes
  vars:
    app_user: ubuntu
    app_name: flask_dashboard
    app_dir: /home/{{ app_user }}/{{ app_name }}
    
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        
    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - nginx
          - git
        state: present
        
    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'
        
    - name: Copy application files
      copy:
        src: "{{ item }}"
        dest: "{{ app_dir }}/"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0644'
      with_items:
        - app.py
        - wsgi.py
        - requirements.txt
        
    - name: Create templates directory
      file:
        path: "{{ app_dir }}/templates"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'
        
    - name: Copy template files
      copy:
        src: templates/
        dest: "{{ app_dir }}/templates/"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0644'
        
    - name: Create Python virtual environment
      command: python3 -m venv "{{ app_dir }}/venv"
      become_user: "{{ app_user }}"
      args:
        creates: "{{ app_dir }}/venv"
        
    - name: Install Python requirements
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        virtualenv: "{{ app_dir }}/venv"
      become_user: "{{ app_user }}"
      
    - name: Create Gunicorn service file
      template:
        src: gunicorn.service.j2
        dest: /etc/systemd/system/{{ app_name }}.service
        mode: '0644'
      notify: reload systemd
      
    - name: Create Nginx configuration
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/{{ app_name }}
        mode: '0644'
      notify: restart nginx
      
    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/{{ app_name }}
        dest: /etc/nginx/sites-enabled/{{ app_name }}
        state: link
      notify: restart nginx
      
    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx
      
    - name: Start and enable Gunicorn service
      systemd:
        name: "{{ app_name }}"
        state: started
        enabled: yes
        daemon_reload: yes
        
    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes
        
  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes
        
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
